-- OpiOpe V21 security hardening

create table if not exists public.teacher_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'invited' check (status in ('invited','active','suspended')),
  mfa_required boolean not null default true,
  invited_by uuid references auth.users(id),
  invited_at timestamptz not null default now(),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.teacher_access enable row level security;
-- No client policies on purpose. Teacher access is administered by trusted server/admin workflows only.

create table if not exists public.security_rate_limits (
  key_hash text primary key,
  hit_count integer not null default 0,
  window_started_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.security_rate_limits enable row level security;
-- No client policies. Service-role only.

create or replace function public.consume_rate_limit(
  p_key text,
  p_window_seconds integer,
  p_max_hits integer
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.security_rate_limits%rowtype;
  now_ts timestamptz := now();
begin
  if p_window_seconds < 1 or p_max_hits < 1 then
    return false;
  end if;

  select * into current_row
  from public.security_rate_limits
  where key_hash = p_key
  for update;

  if not found then
    insert into public.security_rate_limits(key_hash, hit_count, window_started_at, updated_at)
    values (p_key, 1, now_ts, now_ts);
    return true;
  end if;

  if current_row.window_started_at + make_interval(secs => p_window_seconds) <= now_ts then
    update public.security_rate_limits
      set hit_count = 1, window_started_at = now_ts, updated_at = now_ts
      where key_hash = p_key;
    return true;
  end if;

  if current_row.hit_count >= p_max_hits then
    return false;
  end if;

  update public.security_rate_limits
    set hit_count = hit_count + 1, updated_at = now_ts
    where key_hash = p_key;
  return true;
end;
$$;

revoke all on function public.consume_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;

create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.security_audit_log enable row level security;
-- Service-role only. Do not expose directly to clients.

create index if not exists security_audit_log_actor_idx on public.security_audit_log(actor_user_id, created_at desc);
create index if not exists security_audit_log_event_idx on public.security_audit_log(event_type, created_at desc);

